name: courseven
description: "CourSEVEN - Clean Architecture Flutter App"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6

  # HTTP & Network
  dio: ^5.3.2
  http: ^1.1.0
  connectivity_plus: ^5.0.1

  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Dependency Injection
  get_it: ^7.6.4

  # JSON Serialization
  json_annotation: ^4.8.1

  # Utils
  logger: ^2.0.2+1
  intl: ^0.18.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    # Ensure .env is bundled so flutter_dotenv can load it on device
    - .env
